src/Entity/Signalement.php
<?php

namespace App\Entity;

use App\Repository\SignalementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SignalementRepository::class)
 */
class Signalement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $motif;

    /**
     * @ORM\ManyToOne(targetEntity=Produit::class, inversedBy="signalements")
     */
    private $Produit;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="signalements")
     */
    private $Utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity=Commentaires::class, inversedBy="signalements")
     */
    private $Commentaires;

    /**
     * @ORM\ManyToOne(targetEntity=Entreprise::class, inversedBy="signalements")
     */
    private $Entreprise;

    /**
     * @ORM\ManyToOne(targetEntity=Message::class, inversedBy="signalements")
     */
    private $Message;

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMotif(): ?string
    {
        return $this->motif;
    }

    public function setMotif(?string $motif): self
    {
        $this->motif = $motif;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->Produit;
    }

    public function setProduit(?Produit $Produit): self
    {
        $this->Produit = $Produit;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->Utilisateur;
    }

    public function setUtilisateur(?Utilisateur $Utilisateur): self
    {
        $this->Utilisateur = $Utilisateur;

        return $this;
    }

    public function getCommentaires(): ?Commentaires
    {
        return $this->Commentaires;
    }

    public function setCommentaires(?Commentaires $Commentaires): self
    {
        $this->Commentaires = $Commentaires;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->Entreprise;
    }

    public function setEntreprise(?Entreprise $Entreprise): self
    {
        $this->Entreprise = $Entreprise;

        return $this;
    }

    public function getMessage(): ?Message
    {
        return $this->Message;
    }

    public function setMessage(?Message $Message): self
    {
        $this->Message = $Message;

        return $this;
    }
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 * @UniqueEntity(fields={"email"}, message="Cette adresse mail est déjà utilisée.")
 * @UniqueEntity(fields={"telephone"}, message="Ce numéro de téléphone existe déjà. Veuillez vous connecter à votre compte ou en sélectionnez un autre numéro.")
 */
class Utilisateur implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     */
    private $email;

//    Pour le premier utilisateur, passe le role en : ROLE_ADMIN
    /**
     * @ORM\Column(type="json")
     *
     */
    private $roles = ['ROLE_USER'];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\Regex("/^(?:(?:\+|00)33[\s.-]{0,3}(?:\(0\)[\s.-]{0,3})?|0)[1-9](?:(?:[\s.-]?\d{2}){4}|\d{2}(?:[\s.-]?\d{3}){2})$/")
     */
    private $telephone;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vendeur;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\ManyToOne(targetEntity=Ville::class, inversedBy="utilisateurs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ville;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToOne(targetEntity=Entreprise::class, inversedBy="utilisateur", cascade={"persist", "remove"})
     */
    private $entreprise;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="utilisateur")
     */
    private $commandes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activationToken;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tokenMDP;

    /**
     * @ORM\ManyToOne(targetEntity=AdresseLivraison::class, inversedBy="utilisateurs")
     */
    private $adresseLivraison;

    /**
     * @ORM\OneToMany(targetEntity=SousCommande::class, mappedBy="Utilisateur", orphanRemoval=true)
     */
    private $sousCommandes;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Actif;

    /**
     * @ORM\ManyToMany(targetEntity=Conversation::class, mappedBy="user")
     * @ORM\OrderBy({"lastMessage" = "DESC"})
     */
    private $conversations;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="utilisateur")
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity=Signalement::class, mappedBy="Utilisateur")
     */
    private $signalements;


    public function __construct()
    {
        $this->commandes = new ArrayCollection();
        $this->sousCommandes = new ArrayCollection();
        $this->conversations = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->signalements = new ArrayCollection();
    }

    public function isAuthorProduit (Produit $produit){
        if ($this == $produit->getEntreprise()->getUtilisateur()){
            return true;
        }
        return false;
    }

    public function getid(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }



    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getVendeur(): ?bool
    {
        return $this->vendeur;
    }

    public function setVendeur(bool $vendeur): self
    {
        $this->vendeur = $vendeur;

        return $this;
    }


    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?Ville
    {
        return $this->ville;
    }

    public function setVille(?Ville $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
    public function __toString()
    {
        return $this->nom;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUtilisateur($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUtilisateur() === $this) {
                $commande->setUtilisateur(null);
            }
        }

        return $this;
    }

    public function getActivationToken(): ?string
    {
        return $this->activationToken;
    }

    public function setActivationToken(?string $activationToken): self
    {
        $this->activationToken = $activationToken;

        return $this;
    }

    public function getTokenMDP(): ?string
    {
        return $this->tokenMDP;
    }

    public function setTokenMDP(?string $tokenMDP): self
    {
        $this->tokenMDP = $tokenMDP;

        return $this;
    }

    public function getAdresseLivraison(): ?AdresseLivraison
    {
        return $this->adresseLivraison;
    }

    public function setAdresseLivraison(?AdresseLivraison $adresseLivraison): self
    {
        $this->adresseLivraison = $adresseLivraison;

        return $this;
    }

    /**
     * @return Collection|SousCommande[]
     */
    public function getSousCommandes(): Collection
    {
        return $this->sousCommandes;
    }

    public function addSousCommande(SousCommande $sousCommande): self
    {
        if (!$this->sousCommandes->contains($sousCommande)) {
            $this->sousCommandes[] = $sousCommande;
            $sousCommande->setUtilisateur($this);
        }

        return $this;
    }

    public function removeSousCommande(SousCommande $sousCommande): self
    {
        if ($this->sousCommandes->removeElement($sousCommande)) {
            // set the owning side to null (unless already changed)
            if ($sousCommande->getUtilisateur() === $this) {
                $sousCommande->setUtilisateur(null);
            }
        }

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->Actif;
    }

    public function setActif(?bool $Actif): self
    {
        $this->Actif = $Actif;

        return $this;
    }

    /**
     * @return Collection<int, Conversation>
     */


    public function getConversations(): Collection
    {
        return $this->conversations;
    }

    public function addConversation(Conversation $conversation): self
    {
        if (!$this->conversations->contains($conversation)) {

templates/inc/__MessagesFlashs.html.twig
{% for message in app.flashes('danger') %}
    <div class="alert alert-danger" role="alert">{{ message }}</div>
{% endfor %}
{% for message in app.flashes('warning') %}
    <div class="alert alert-warning" role="alert">{{ message }}</div>
{% endfor %}
{% for message in app.flashes('message') %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
{% endfor %}

templates/inc/__card.html.twig
{% for produit in  produits %}
    {% if produit.entreprise.utilisateur.vendeur %}
        {% if produit.entreprise.utilisateur.actif %}
            <div class="article">
                {% if produit.fichiers is not empty %}
                    <img class="article__img" src="{{ asset('img/ProduitPhoto/'~produit.fichiers[0].urlFichier) }}" alt="photo-produit" height="auto">
                {% else %}
                    <img class="article__img" src="{{ asset('img/Erreurs/notFound.png') }}" alt="photo-erreur">
                {% endif %}
                <h5 class="article__info">{{ produit.nomArticle }}</h5>
                <div class="article__info">
                    {{ produit.description|length > 20? produit.description|slice(0, 20) ~ '...' : produit.description}}
                </div>
                <div class="article__info card-prix">
                    {{ produit.prix ~ ' €' }}
                </div>
                <div class="article__info">
                    {% if app.user %}
                        {% if app.user.entreprise == produit.entreprise %}
                            <a href="{{ path('modifierProduit', {'id' : produit.id} ) }}"
                               class="btn button">Modifier</a>
                        {% else %}
                            <a href="{{ path('produit_detail', {'id' : produit.id} ) }}"
                               class="btn button bouton-submit">
                                <i class="bi bi-search"></i>
                            </a>
                            <a href="{{ path('panier_add', {'id' : produit.id , 'provenance' : app.request.attributes.get('_route')}  ) }}"
                               class="btn button bouton-submit">
                                <i class="bi bi-cart-plus"></i>
                            </a>
                        {% endif %}
                    {% else %}
                        <a href="{{ path('produit_detail', {'id' : produit.id} ) }}" class="btn button bouton-submit">Détails</a>
                    {% endif %}
                </div>
            </div>

        {% endif %}
    {% endif %}
{% endfor %}

templates/inc/__footer.html.twig
<footer>
    <div class="administratif">
            <a href="{{ path('CGV') }}">Conditions Générales de Vente</a>
            <a href="{{ path('ML') }}">Mentions Légales</a>
    </div>
    <p class="copyright">Copyright 2021</p>
</footer>

templates/inc/__head.html.twig
<head>
    <meta charset="UTF-8">
    <!-- Bootstrap CSS -->
    {% block stylesheets %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        {#{{ encore_entry_link_tags('app') }}#}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</head>

templates/inc/nav.html.twig
<nav class="navbar navbar-expand navbar-light bg-green">

    <img src="{{ asset('img/logo/Logo-final.svg') }}" alt="image" class="logo"></a>

    <h1 class="titre">Made in Loire / Haute-Loire</h1>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{{ path('Accueil') }}">Accueil <span class="sr-only"></span></a>
            </li>

            {% if is_granted("ROLE_ADMIN") %}
                <li class="">
                    <a class="nav-link" href="{{ path('adminBoard') }}">Panneau d'administration</a>
                </li>
            {% endif %}
            {% if app.user %}
                <div class="dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        {{ 'Mon Compte' }}
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        <li class="animation"><a class="dropdown-item "href="{{ path('utilisateur_modification', {'id' : app.user.id} ) }}">
                                Mes informations
                            </a>
                        </li>
                        <li class="animation"><a class="dropdown-item "
                                                 href="{{ path('app_chat_index')}}">Mes discussions</a></li>
                        {% if app.user.entreprise and app.user.vendeur %}
                            <li><a class="dropdown-item" href="{{ path('entreprise_show', {'id':  app.user.entreprise.id}) }}">Mon entreprise </a></li>
                            <li><a class="dropdown-item"
                                   href="{{ path('produitPartenaire', {'id' : app.user.entreprise.id} ) }}">Ma
                                    vitrine</a></li>
                        {% else %}
                            {% if not app.user.vendeur and app.user.entreprise %}
                                <li><a class="dropdown-item" href="{{ path('Partenaire') }}">Mon entreprise </a></li>
                            {% else %}
                                <li class="nav-item animation">
                                    <a class="dropdown-item" href="{{ path('InscriptionFournisseur') }}">Devenir
                                        partenaire </a>
                                </li>
                            {% endif %}
                        {% endif %}
                        {% if app.user.entreprise is not empty %}
                            <li class="nav-item animation">
                                <a class="dropdown-item" href="{{ path('afficheSousCommandes') }}">Mes ventes</a>
                                <a class="dropdown-item" href="{{ path('affichecommandesClient') }}">Mes commandes</a>
                            </li>
                        {% else %}
                            <a class="dropdown-item" href="{{ path('affichecommandesClient') }}">Mes commandes</a>
                        {% endif %}
                        {% if app.user %}
                            <li class="nav-item animation">
                                <a class="dropdown-item" href="{{ path('app_logout') }}">Se déconnecter</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            {% else %}
                <div class="btn-group">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Se connecter
                    </button>

                    <div class="dropdown-menu">
                        <form class="px-2 py-3" action="{{ path('app_login') }}" method="post">
                            <div class="mb-3">
                                <label for="inputEmail" class="form-label">Email</label>
                                <input type="email" value="" name="email" id="inputEmail" class="form-control"
                                       autocomplete="email" required autofocus
                                       placeholder="email@example.com">
                            </div>

                            <div class="mb-2">
                                <label for="inputPassword" class="form-label">Mot de passe</label>
                                <input type="password" name="password" id="inputPassword" class="form-control"
                                       autocomplete="current-password" required>
                                <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
                            </div>

                            <div class="mb-2">
                                <div class="form-check">
                                    <input type="checkbox" name="_remember_me">
                                    <label class="form-check-label" for="dropdownCheck">
                                        Rester connecté
                                    </label>
                                </div>
                            </div>

                            <div class="container-btn">
                            <button type="submit" class="btn button bouton-submit">Connexion</button>
                            </div>

                        </form>

                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ path('app_register') }}">Inscription</a>
                        <a class="dropdown-item" href="{{ path('motDePasseOublie') }}">Mot de passe oublié ?</a>
                    </div>
                </div>
            {% endif %}
            <li class="nav-icon ">
                <a class="nav-link" href="{{ path('panier_index') }}"> <i class="bi bi-cart"></i> Panier</a>
            </li>
        </ul>
    </div>
</nav>

<img class="banniere" src="{{ asset('img/logo/bannière-2.png') }}">